FarmBuddyCityMunTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: FarmBuddyCityMunTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: "id"
        AttributeType: "N"
      - AttributeName: provCode
        AttributeType: S
      - AttributeName: regCode
        AttributeType: S
    KeySchema:
      - AttributeName: "id"
        KeyType: "HASH"
    GlobalSecondaryIndexes:
      - IndexName: ProvCodeAndRegCode
        KeySchema:
          - AttributeName: provCode
            KeyType: HASH
          - AttributeName: regCode
            KeyType: RANGE
        Projection:
          ProjectionType: ALL